name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "tag=v$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git tag "v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"

  build:
    needs: prepare

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64

          - os: macos-15-intel
            platform: macos
            arch: x64

          - os: macos-26
            platform: macos
            arch: arm64

          - os: windows-latest
            platform: windows
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dsh-${{ matrix.platform }}-${{ matrix.arch }}
          path: target/dsh
          retention-days: 1

  release:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.prepare.outputs.tag }}
          name: ${{ needs.prepare.outputs.version }}
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: ${{ contains(steps.version.outputs.version, 'rc') || contains(steps.version.outputs.version, 'alpha') || contains(steps.version.outputs.version, 'beta') }}
          generate_release_notes: true
          files: |
            artifacts/dsh-linux-x64/dsh
            artifacts/dsh-macos-x64/dsh
            artifacts/dsh-macos-arm64/dsh
            artifacts/dsh-windows-x64/dsh.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}